"""Historical lands: each migrating people's AI conquest preference for the Roman land it historically settled, and the
scripted trigger that asks "is this area that host's historical land?". Edit HISTORICAL_LANDS, then python script/run.py."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools"))
from pdx.api import AreaTrig, CountryTrig
from pdx.objects import Doc, Loc
from pdx.objects_defs import Defs

# tag -> vanilla area keys (without `_area`): only land that was Roman in 395, where the people really settled.
# TGI has none: the Thuringians never settled inside the Empire.
HISTORICAL_LANDS: dict[str, list[str]] = {
    "VIS": ["guyenne", "gascony", "languedoc", "catalonia", "toledo", "castile"],  # Aquitaine 418, Septimania, Tarraconensis
    "HAS": ["galicia", "tunis", "algiers"],  # Gallaecia 409, then Carthage 439 and Numidia
    "SLX": ["andalusia", "granada"],  # Baetica 409, before Gunderic's crossing to Africa
    "QAD": ["galicia", "north_portugal"],  # the Quadi joined the Suebi in Gallaecia
    "ALM": ["alsace", "upper_rhine", "eastern_switzerland", "central_switzerland"],  # Strasbourg and Raetia, 5th century
    "BGD": ["hesse", "western_switzerland", "franche_comte", "savoy", "lyonnais", "burgundy"],  # Worms 413, Sapaudia 443, Lyon 461
    "FRK": ["rhineland", "lorraine", "wallonia"],  # the Ripuarians: Cologne and Trier
    "SLF": ["brabant", "flanders", "wallonia", "picardy", "ile_de_france", "champagne"],  # Toxandria 358, Tournai, Clovis
    "FRS": ["holland"],  # Batavia's coast
    "SAX": ["home_counties", "west_country"],  # Sussex, Essex and Wessex
    "AGL": ["east_anglia", "midlands", "northumbria"],  # East Anglia, Mercia, Northumbria
    "MKM": ["transdanubia"],  # Fritigil's Marcomanni in Pannonia, c. 396
    "LGB": ["transdanubia", "lombardy", "veneto", "emilia"],  # Pannonia 526, Italy 568
    "RUG": ["austria"],  # Noricum Ripensis, after Attila
    "SCR": ["bulgaria"],  # Scythia Minor, 409
    "GEP": ["slavonia"],  # Sirmium, 454
    "CRP": ["bulgaria"],  # the Carpi resettled in Moesia
    "IAZ": ["transdanubia"],  # the Sarmatians of Pannonia Valeria
}

PREF_FILE = "in_game/common/area_preferences/tfe_historical_lands.txt"
TRIG_FILE = "in_game/common/scripted_triggers/tfe_historical_lands.txt"
SETUP_FILE = "main_menu/setup/start/25_area_preferences.txt"
LOC_FILE = "main_menu/localization/english/tfe_historical_lands_l_english.yml"
WRITER = "script/defs_historical_lands.py"


def pref(tag: str) -> str:
    return f"tfe_{tag.lower()}_historical_lands"


def preferences() -> str:
    doc = Doc()
    doc.note(f"TFE: generated by {WRITER}. A migrating people's AI wants the Roman land it historically settled.")
    for tag, areas in HISTORICAL_LANDS.items():
        with doc.entry(pref(tag)) as p:
            p.field("preference_type", "conquest")
            p.field("modifier", 10)
            for a in areas:
                p.field("area", f"{a}_area")
    return doc.text()


def localisation() -> str:
    """The preference's line in a country's AI Area Preferences tooltip, naming its areas by their own (Latin) loc keys."""
    loc = Loc()
    for tag, areas in HISTORICAL_LANDS.items():
        loc.add(pref(tag), "Seek the lands of their people: " + ", ".join(f"${a}_area$" for a in areas))
    return loc.text()


def setup() -> str:
    doc = Doc()
    doc.note(f"TFE: generated by {WRITER}. Each migrating people starts with its historical-lands preference.")
    with doc.entry("countries") as top, top.block("countries") as cs:
        for tag in HISTORICAL_LANDS:
            with cs.block(tag) as c, c.block("area_preferences") as ap:
                ap.raw(pref(tag))
    return doc.text()


def triggers() -> str:
    d = Defs()
    d.note(f"TFE: generated by {WRITER}.\n"
           "Scope: an area. True when it is historical land of the country $WHO$ (the table in that script, the same areas as\n"
           "area_preferences/tfe_historical_lands.txt). Call: scope:area = { tfe_is_historical_land_of = { WHO = scope:host } }")
    with d.trigger("tfe_is_historical_land_of", AreaTrig) as t, t.or_() as o:
        for tag, areas in HISTORICAL_LANDS.items():
            with o.and_() as a:
                with a.link("$WHO$", CountryTrig) as c:
                    c.tag(tag)
                with a.or_() as any_area:
                    for area in areas:
                        any_area.compare("this", "=", f"area:{area}_area")
    return d.text()


def outputs():
    """{repo-relative path: text}; run.py writes each, with a BOM except in the start files."""
    return {PREF_FILE: preferences(), TRIG_FILE: triggers(), SETUP_FILE: setup(), LOC_FILE: localisation()}

