"""Write docs/INDEX.md, the map of every script and localisation file: `python tools/gen_index.py`.

CodeGraph reads our Python and yml but not PDXScript, so this lists what grep can miss: each `.txt`'s purpose (its
header comment), what generates it, and its top-level keys with line numbers (events, effects, decisions ...).
A test fails when it is stale; rerun after adding or renaming anything.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "script"))
sys.path.insert(0, str(ROOT / "tools"))
OUT = ROOT / "docs" / "INDEX.md"

# Written by tools/*.py rather than script/*.py (longest prefix wins).
TOOL_WRITES = {
    "main_menu/setup/395/": "tools/borders.py",
    "in_game/setup/countries/tfe_countries.txt": "tools/borders.py",
    "in_game/common/town_setups/tfe_unfortified.txt": "tools/borders.py",
    "in_game/common/formable_countries/00_formable_countries.txt": "tools/borders.py (vanilla copy)",
    "main_menu/localization/english/tfe_countries_l_english.yml": "tools/borders.py",
    "in_game/map_data/": "tools/location_templates.py",
    "main_menu/localization/english/replace/tfe_place_names_l_english.yml": "tools/place_names.py",
    "main_menu/localization/english/replace/tfe_town_names_l_english.yml": "tools/place_names.py",
}
HUGE = ("main_menu/setup/395/", "in_game/map_data/")  # thousands of keys: say what it is, not every key
KEY = re.compile(r"""^([^\s#={}"]+)\s*=\s*\{""")


def top_level_keys(text):
    """(line number, key) of every `key = {` at brace depth 0, ignoring comments and quoted strings."""
    depth, keys = 0, []
    for n, line in enumerate(text.splitlines(), 1):
        code = re.sub(r'"[^"\n]*"', '""', line.split("#", 1)[0])
        if depth == 0 and (m := KEY.match(code)):
            keys.append((n, m.group(1)))
        depth += code.count("{") - code.count("}")
    return keys


def header(text):
    """The first comment block, joined: what the file is for."""
    out = []
    for line in text.lstrip("﻿").splitlines():
        if line.startswith("#"):
            out.append(line.lstrip("# ").strip())
        elif out or line.strip():
            break
    return " ".join(out)


def generators():
    import run
    made = {rel: f"script/{name}.py" for name, mod in run.modules() for rel in mod.outputs()}
    return made


def build():
    made = generators()

    def generated_by(rel):
        if rel in made:
            return made[rel]
        hits = [p for p in TOOL_WRITES if rel.startswith(p)]
        return TOOL_WRITES[max(hits, key=len)] if hits else None

    lines = [
        "# TFE index", "",
        "Generated by `python tools/gen_index.py` (a test fails when it is stale): never edit by hand.", "",
        "Look here before concluding something does not exist. Edit the generator named for a file, never the file;",
        "a file with no generator is hand-written PDXScript. CodeGraph covers `script/` and `tools/` Python and yml;",
        "this covers the `.txt` script it cannot read. Vanilla EU5 is not in this repo (see CLAUDE.md for where).", "",
        "## Generators and what they write", "",
    ]
    by_gen = {}
    for rel, gen in sorted(made.items()):
        by_gen.setdefault(gen, []).append(rel)
    for gen, rels in by_gen.items():
        lines.append(f"- `{gen}` writes: " + ", ".join(f"`{r}`" for r in rels))
    lines += ["", "## Script files (`.txt`): purpose, then top-level keys as `path:line key`", ""]
    txts = sorted(p for p in (ROOT / "in_game").rglob("*.txt")) + sorted(p for p in (ROOT / "main_menu").rglob("*.txt"))
    for p in txts:
        rel = p.relative_to(ROOT).as_posix()
        text = p.read_text(encoding="utf-8-sig")
        by = generated_by(rel)
        lines += [f"### {rel}", f"{len(text.splitlines())} lines" + (f", generated by `{by}`" if by else ", hand-written")]
        if h := header(text):
            lines.append(h)
        if rel.startswith(HUGE):
            lines.append("(too many keys to list: grep the file)")
        else:
            lines += [f"{rel}:{n} {k}" for n, k in top_level_keys(text)]
        lines.append("")
    lines += ["## Localisation files (`.yml`): keys are `key:` lines, grep them", ""]
    for p in sorted((ROOT / "main_menu" / "localization").rglob("*.yml")):
        rel = p.relative_to(ROOT).as_posix()
        n = len(re.findall(r"^ [^\s#:]+:", p.read_text(encoding="utf-8-sig"), re.M))
        lines.append(f"- `{rel}`: {n} keys" + (f", generated by `{generated_by(rel)}`" if generated_by(rel) else ""))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUT.write_text(build(), encoding="utf-8", newline="\n")
    print("wrote", OUT.relative_to(ROOT))
