# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy", "pillow"]
# ///
"""TFE location templates: vanilla's, with what the land was good for in 395.

  uv run tools/location_templates.py     rewrite in_game/map_data/location_templates.txt from vanilla's

A template's `modifier` is the location's own: it shows as a badge on the goods marker in the raw-material map mode
and in the location panel (vanilla: Almaden's mercury, Skane's herring). Rerun after a patch changes vanilla's file.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import borders as b

OUT = b.MOD / "in_game/map_data/location_templates.txt"

# Africa's grain filled the annona of Rome: Carthage, the Bagradas valley and the wheat towns of Byzacena.
# Vanilla's 1337 goods for five of them (dyes, sugar, olives, clay, legumes) were grain fields in 395.
GRANARIES = ("tunis", "mateur", "tebourba", "medjez_el_bab", "beja_TUN", "el_kef", "el_fahs", "tebessa", "sbiba",
             "kairouan", "gabes")
# Pannonia Prima, Valeria, Savia and Secunda: the legions' best recruits, and most of their emperors
PANNONIA = ("transdanubia_area", "slavonia_area")
# Rome ate African bread: a fifth of Italy's wheat land (9 of 44) had gone to the villas' vines and herds. All in
# Italia Suburbicaria, which the annona fed; the Po valley still grew grain for the court, and Sicily and Sardinia were
# granaries themselves. Lucania, Bruttium and Samnium sent Rome its pork dole; Apulia its wool.
ITALIAN_VILLAS = {
    "gaeta": "wine",           # Caecuban and Falernian
    "fermo": "wine",           # Picenum
    "viterbo": "wine",         # Etruria
    "grosseto": "livestock",   # the Maremma
    "campagna": "livestock",   # Lucania
    "benevento": "livestock",  # Samnium
    "cassano": "livestock",    # Bruttium
    "foggia": "wool",          # Apulia
    "larino": "wool",
}


def overrides(anc, topo, unownable):
    out = {l: {"raw_material": "wheat", "modifier": "tfe_granary_of_rome"} for l in GRANARIES}
    out |= {l: {"raw_material": g} for l, g in ITALIAN_VILLAS.items()}
    for l, path in anc.items():
        if len(path) > 3 and path[3] in PANNONIA and topo.get(l) in b.LAND_TOPO and l not in unownable:
            out[l] = {"modifier": "tfe_pannonian_recruiting_grounds"}
    return out


def apply(text, changes):
    seen = set()
    def one(m):
        name, body = m.group(1), m.group(2)
        if name not in changes:
            return m.group(0)
        seen.add(name)
        for k, v in changes[name].items():
            if re.search(rf"\b{k} = \w+", body):
                body = re.sub(rf"\b{k} = \w+", f"{k} = {v}", body)
            else:
                body = f" {k} = {v}" + body
        return f"{name} = {{{body}}}"
    text = re.sub(r"^(\w+) = \{([^{}\n]*)\}", one, text, flags=re.M)
    missing = set(changes) - seen
    assert not missing, sorted(missing)
    return text


def build():
    vanilla = (b.MAP / "location_templates.txt").read_text(encoding="utf-8-sig")
    changes = overrides(b.load_hierarchy(), b.load_topography(), b.load_unownable())
    return "# GENERATED by tools/location_templates.py from vanilla's - do not edit\n" + apply(vanilla, changes)


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8-sig")
    print(f"wrote {OUT}")
